/*
 * ONTAP REST API
 *
 * ONTAP 9.6 adds support for an expansive RESTful API. The documentation below provides information about the types of API calls available to you, as well as details about using each API endpoint. You can learn more about the ONTAP REST API and ONTAP in the ONTAP 9 Documentation Center:  http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-rest-api/home.html. NetApp welcomes your comments and suggestions about the ONTAP REST API and the documentation for its use.</br> **Using the ONTAP 9.6 REST API online documentation** Each API method includes usage examples, as well as a model that displays all the required and optional properties supported by the method. Click the _Model_ link, available with each API method, to see all the required and optional properties supported by each method. 
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type AggregateSpare struct {
	// The checksum type that has been assigned to the spares
	ChecksumStyle string `json:"checksum_style,omitempty"`
	// Disk class of spares
	DiskClass string `json:"disk_class,omitempty"`
	// Available RAID protections and their restrictions
	LayoutRequirements []LayoutRequirement `json:"layout_requirements,omitempty"`
	Node *AggregateSpareNode `json:"node,omitempty"`
	// Usable size of each spare in bytes
	Size int32 `json:"size,omitempty"`
	// SyncMirror spare pool
	SyncmirrorPool string `json:"syncmirror_pool,omitempty"`
	// Total number of usable spares
	Usable int32 `json:"usable,omitempty"`
}
