/*
 * ONTAP REST API
 *
 * ONTAP 9.6 adds support for an expansive RESTful API. The documentation below provides information about the types of API calls available to you, as well as details about using each API endpoint. You can learn more about the ONTAP REST API and ONTAP in the ONTAP 9 Documentation Center:  http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-rest-api/home.html. NetApp welcomes your comments and suggestions about the ONTAP REST API and the documentation for its use.</br> **Using the ONTAP 9.6 REST API online documentation** Each API method includes usage examples, as well as a model that displays all the required and optional properties supported by the method. Click the _Model_ link, available with each API method, to see all the required and optional properties supported by each method. 
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// MAX Data application using SAN.
type MaxdataOnSan struct {
	// Type of the application that is being deployed on the L2. Required in the POST body
	AppType string `json:"app_type,omitempty"`
	// application-components. Optional in the POST or PATCH body
	ApplicationComponents []MaxdataOnSanApplicationComponents `json:"application_components,omitempty"`
	Metadata []MaxdataOnSanMetadata `json:"metadata,omitempty"`
	// The list of initiator groups to create. Optional in the POST or PATCH body
	NewIgroups []MaxdataOnSanNewIgroups `json:"new_igroups,omitempty"`
	// The OnCommand System Manager URL for this application
	OcsmUrl string `json:"ocsm_url,omitempty"`
	// The name of the host OS running the application. Required in the POST body
	OsType string `json:"os_type,omitempty"`
}
