/*
 * ONTAP REST API
 *
 * ONTAP 9.6 adds support for an expansive RESTful API. The documentation below provides information about the types of API calls available to you, as well as details about using each API endpoint. You can learn more about the ONTAP REST API and ONTAP in the ONTAP 9 Documentation Center:  http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-rest-api/home.html. NetApp welcomes your comments and suggestions about the ONTAP REST API and the documentation for its use.</br> **Using the ONTAP 9.6 REST API online documentation** Each API method includes usage examples, as well as a model that displays all the required and optional properties supported by the method. Click the _Model_ link, available with each API method, to see all the required and optional properties supported by each method. 
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Configuration information for the cloud storage portion of the aggregate. This is referred to as the capacity tier.
type AggregateCloudStorage struct {
	// Aggregate is eligible for a cloud store to be attached.
	AttachEligible bool `json:"attach_eligible,omitempty"`
	// Configuration information for each cloud storage portion of the aggregate.
	Stores []CloudStorageTier `json:"stores,omitempty"`
	// The percentage of space in the performance tier that must be used before data is tiered out to the cloud store. Only valid for PATCH operations.
	TieringFullnessThreshold int32 `json:"tiering_fullness_threshold,omitempty"`
}
