/*
 * ONTAP REST API
 *
 * ONTAP 9.6 adds support for an expansive RESTful API. The documentation below provides information about the types of API calls available to you, as well as details about using each API endpoint. You can learn more about the ONTAP REST API and ONTAP in the ONTAP 9 Documentation Center:  http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-rest-api/home.html. NetApp welcomes your comments and suggestions about the ONTAP REST API and the documentation for its use.</br> **Using the ONTAP 9.6 REST API online documentation** Each API method includes usage examples, as well as a model that displays all the required and optional properties supported by the method. Click the _Model_ link, available with each API method, to see all the required and optional properties supported by each method. 
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ontap
// Vscan Vscan can be used to protect data from being compromised by viruses or other malicious code. This combines best-in-class third-party antivirus software with ONTAP features that give you the flexibility you need to control which files get scanned and when. Storage systems offload scanning operations to external servers hosting antivirus software from thirdparty vendors. An Antivirus Connector on the external server handles communications between the storage system and the antivirus software.
type Vscan struct {
	Links InlineResponse201Links `json:"_links,omitempty"`
	// Discards the cached information of the files that have been successfully scanned. Once the cache is cleared, files are scanned again when they are accessed. PATCH only
	CacheClear bool `json:"cache_clear,omitempty"`
	// Specifies whether or not Vscan is enabled on the SVM.
	Enabled bool `json:"enabled,omitempty"`
	OnAccessPolicies []VscanOnAccess `json:"on_access_policies,omitempty"`
	OnDemandPolicies []VscanOnDemand `json:"on_demand_policies,omitempty"`
	ScannerPools []VscanScannerPool `json:"scanner_pools,omitempty"`
	Svm AuditSvm `json:"svm,omitempty"`
}
