/*
 * ONTAP REST API
 *
 * ONTAP 9.6 adds support for an expansive RESTful API. The documentation below provides information about the types of API calls available to you, as well as details about using each API endpoint. You can learn more about the ONTAP REST API and ONTAP in the ONTAP 9 Documentation Center:  http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-rest-api/home.html. NetApp welcomes your comments and suggestions about the ONTAP REST API and the documentation for its use.</br> **Using the ONTAP 9.6 REST API online documentation** Each API method includes usage examples, as well as a model that displays all the required and optional properties supported by the method. Click the _Model_ link, available with each API method, to see all the required and optional properties supported by each method. 
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ontap
// FcPort A Fibre Channel (FC) port is the physical port of an FC adapter on an ONTAP cluster node that can be connected to an FC network to provide FC network connectivity. An FC port defines the location of an FC interface within the ONTAP cluster. 
type FcPort struct {
	Links InlineResponse201Links `json:"_links,omitempty"`
	// A description of the FC port. 
	Description string `json:"description,omitempty"`
	// The administrative state of the FC port. If this property is set to _false_, all FC connectivity to FC interfaces are blocked. Optional in PATCH. 
	Enabled bool `json:"enabled,omitempty"`
	Fabric FcPortFabric `json:"fabric,omitempty"`
	// The FC port name. 
	Name string `json:"name,omitempty"`
	Node InlineResponse201Node `json:"node,omitempty"`
	// The physical network protocol of the FC port. 
	PhysicalProtocol string `json:"physical_protocol,omitempty"`
	Speed FcPortSpeed `json:"speed,omitempty"`
	// The operational state of the FC port. - startup - The port is booting up. - link_not_connected - The port has finished initialization, but a link with the fabric is not established. - online - The port is initialized and a link with the fabric has been established. - link_disconnected - The link was present at one point on this port but is currently not established. - offlined_by_user - The port is administratively disabled. - offlined_by_system - The port is set to offline by the system. This happens when the port encounters too many errors. - node_offline - The state information for the port cannot be retrieved. The node is offline or inaccessible. 
	State string `json:"state,omitempty"`
	// The network protocols supported by the FC port. 
	SupportedProtocols []string `json:"supported_protocols,omitempty"`
	Transceiver FcPortTransceiver `json:"transceiver,omitempty"`
	// The unique identifier of the FC port. 
	Uuid string `json:"uuid,omitempty"`
	// The base world wide node name (WWNN) for the FC port. 
	Wwnn string `json:"wwnn,omitempty"`
	// The base world wide port name (WWPN) for the FC port. 
	Wwpn string `json:"wwpn,omitempty"`
}
