/*
 * ONTAP REST API
 *
 * ONTAP 9.6 adds support for an expansive RESTful API. The documentation below provides information about the types of API calls available to you, as well as details about using each API endpoint. You can learn more about the ONTAP REST API and ONTAP in the ONTAP 9 Documentation Center:  http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-rest-api/home.html. NetApp welcomes your comments and suggestions about the ONTAP REST API and the documentation for its use.</br> **Using the ONTAP 9.6 REST API online documentation** Each API method includes usage examples, as well as a model that displays all the required and optional properties supported by the method. Click the _Model_ link, available with each API method, to see all the required and optional properties supported by each method. 
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ontap
// SnapshotPolicy The Snapshot copy policy object is associated with a read-write volume used to create and delete Snapshot copies at regular intervals.
type SnapshotPolicy struct {
	Links InlineResponse201Links `json:"_links,omitempty"`
	// A comment associated with the Snapshot copy policy.
	Comment string `json:"comment,omitempty"`
	Copies []SnapshotPolicyCopies `json:"copies,omitempty"`
	// Is the Snapshot copy policy enabled?
	Enabled bool `json:"enabled,omitempty"`
	// Name of the Snapshot copy policy.
	Name string `json:"name,omitempty"`
	// Set to \"svm\" when the request is on a data SVM, otherwise set to \"cluster\".
	Scope string `json:"scope,omitempty"`
	Svm AuditSvm `json:"svm,omitempty"`
	Uuid string `json:"uuid,omitempty"`
}
