/*
 * ONTAP REST API
 *
 * ONTAP 9.6 adds support for an expansive RESTful API. The documentation below provides information about the types of API calls available to you, as well as details about using each API endpoint. You can learn more about the ONTAP REST API and ONTAP in the ONTAP 9 Documentation Center:  http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-rest-api/home.html. NetApp welcomes your comments and suggestions about the ONTAP REST API and the documentation for its use.</br> **Using the ONTAP 9.6 REST API online documentation** Each API method includes usage examples, as well as a model that displays all the required and optional properties supported by the method. Click the _Model_ link, available with each API method, to see all the required and optional properties supported by each method. 
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ontap
// RaidGroupDisk struct for RaidGroupDisk
type RaidGroupDisk struct {
	Disk RaidGroupDiskDisk `json:"disk,omitempty"`
	// The position of the disk within the RAID group.
	Position string `json:"position,omitempty"`
	// The state of the disk within the RAID group.
	State string `json:"state,omitempty"`
	// Disk interface type
	Type string `json:"type,omitempty"`
	// Size in bytes that is usable by the aggregate.
	UsableSize int32 `json:"usable_size,omitempty"`
}
