/*
 * ONTAP REST API
 *
 * ONTAP 9.6 adds support for an expansive RESTful API. The documentation below provides information about the types of API calls available to you, as well as details about using each API endpoint. You can learn more about the ONTAP REST API and ONTAP in the ONTAP 9 Documentation Center:  http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-rest-api/home.html. NetApp welcomes your comments and suggestions about the ONTAP REST API and the documentation for its use.</br> **Using the ONTAP 9.6 REST API online documentation** Each API method includes usage examples, as well as a model that displays all the required and optional properties supported by the method. Click the _Model_ link, available with each API method, to see all the required and optional properties supported by each method. 
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ontap
import (
	"time"
)
// License struct for License
type License struct {
	// A flag indicating whether the license is currently being enforced.
	Active bool `json:"active,omitempty"`
	Capacity LicenseCapacity `json:"capacity,omitempty"`
	Compliance LicenseCompliance `json:"compliance,omitempty"`
	// A flag indicating whether the license is in evaluation mode.
	Evaluation bool `json:"evaluation,omitempty"`
	// Date and time when the license expires.
	ExpiryTime time.Time `json:"expiry_time,omitempty"`
	// Cluster, node or license manager that owns the license.
	Owner string `json:"owner,omitempty"`
	// Serial number of the license.
	SerialNumber string `json:"serial_number,omitempty"`
	// Date and time when the license starts.
	StartTime time.Time `json:"start_time,omitempty"`
}
