/*
 * ONTAP REST API
 *
 * ONTAP 9.6 adds support for an expansive RESTful API. The documentation below provides information about the types of API calls available to you, as well as details about using each API endpoint. You can learn more about the ONTAP REST API and ONTAP in the ONTAP 9 Documentation Center:  http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-rest-api/home.html. NetApp welcomes your comments and suggestions about the ONTAP REST API and the documentation for its use.</br> **Using the ONTAP 9.6 REST API online documentation** Each API method includes usage examples, as well as a model that displays all the required and optional properties supported by the method. Click the _Model_ link, available with each API method, to see all the required and optional properties supported by each method. 
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ontap
// KeyServer struct for KeyServer
type KeyServer struct {
	Links InlineResponse201Links `json:"_links,omitempty"`
	// Password credentials for connecting with the key server. This is not audited.
	Password string `json:"password,omitempty"`
	// An array of key servers specified to add multiple key servers to a key manager in a single API call. Valid in POST only and not valid if `server` is provided. 
	Records []KeyServerRecords `json:"records,omitempty"`
	// External key server for key management. If no port is provided, a default port of 5696 is used. Not valid in POST if `records` is provided.
	Server string `json:"server,omitempty"`
	// I/O timeout in seconds for communicating with the key server.
	Timeout int32 `json:"timeout,omitempty"`
	// KMIP username credentials for connecting with the key server.
	Username string `json:"username,omitempty"`
}
