/*
 * ONTAP REST API
 *
 * ONTAP 9.6 adds support for an expansive RESTful API. The documentation below provides information about the types of API calls available to you, as well as details about using each API endpoint. You can learn more about the ONTAP REST API and ONTAP in the ONTAP 9 Documentation Center:  http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-rest-api/home.html. NetApp welcomes your comments and suggestions about the ONTAP REST API and the documentation for its use.</br> **Using the ONTAP 9.6 REST API online documentation** Each API method includes usage examples, as well as a model that displays all the required and optional properties supported by the method. Click the _Model_ link, available with each API method, to see all the required and optional properties supported by each method. 
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ontap
// VolumeMovement Volume movement. All attributes are modify, that is, not writable through POST. Set PATCH state to destination_aggregate to initiate a volume move operation. Volume movement on FlexGroup constituents are not supported.
type VolumeMovement struct {
	// Time window in seconds for cutover. The allowed range is between 30 to 300 seconds.
	CutoverWindow int32 `json:"cutover_window,omitempty"`
	DestinationAggregate DiskAggregates `json:"destination_aggregate,omitempty"`
	// Completion percentage
	PercentComplete string `json:"percent_complete,omitempty"`
	// State of volume move operation. PATCH the state to \"aborted\" to abort the move operation. PATCH the state to \"cutover\" to trigger cutover. PATCH the state to \"paused\" to pause the volume move operation in progress. PATCH the state to \"replicating\" to resume the paused volume move operation. PATCH the state to \"cutover-wait\" to go into cutover manually. Change of state is only supported if volume movement is in progress.
	State string `json:"state,omitempty"`
	// Tiering policy for FabricPool
	TieringPolicy string `json:"tiering_policy,omitempty"`
}
