/*
 * ONTAP REST API
 *
 * ONTAP 9.6 adds support for an expansive RESTful API. The documentation below provides information about the types of API calls available to you, as well as details about using each API endpoint. You can learn more about the ONTAP REST API and ONTAP in the ONTAP 9 Documentation Center:  http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-rest-api/home.html. NetApp welcomes your comments and suggestions about the ONTAP REST API and the documentation for its use.</br> **Using the ONTAP 9.6 REST API online documentation** Each API method includes usage examples, as well as a model that displays all the required and optional properties supported by the method. Click the _Model_ link, available with each API method, to see all the required and optional properties supported by each method. 
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ontap
// IpService the model 'IpService'
type IpService string

// List of ip_service
const (
	CLUSTER_CORE IpService = "cluster_core"
	INTERCLUSTER_CORE IpService = "intercluster_core"
	MANAGEMENT_CORE IpService = "management_core"
	MANAGEMENT_AUTOSUPPORT IpService = "management_autosupport"
	MANAGEMENT_BGP IpService = "management_bgp"
	MANAGEMENT_HTTPS IpService = "management_https"
	MANAGEMENT_SSH IpService = "management_ssh"
	DATA_CORE IpService = "data_core"
	DATA_NFS IpService = "data_nfs"
	DATA_CIFS IpService = "data_cifs"
	DATA_FLEXCACHE IpService = "data_flexcache"
	DATA_ISCSI IpService = "data_iscsi"
)
