/*
 * ONTAP REST API
 *
 * ONTAP 9.6 adds support for an expansive RESTful API. The documentation below provides information about the types of API calls available to you, as well as details about using each API endpoint. You can learn more about the ONTAP REST API and ONTAP in the ONTAP 9 Documentation Center:  http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-rest-api/home.html. NetApp welcomes your comments and suggestions about the ONTAP REST API and the documentation for its use.</br> **Using the ONTAP 9.6 REST API online documentation** Each API method includes usage examples, as well as a model that displays all the required and optional properties supported by the method. Click the _Model_ link, available with each API method, to see all the required and optional properties supported by each method.
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ontap

// NfsServiceProtocolV41Features struct for NfsServiceProtocolV41Features
type NfsServiceProtocolV41Features struct {
	// Specifies whether NFSv4.1 ACLs is enabled.
	AclEnabled bool `json:"acl_enabled,omitempty"`
	// Specifies whether NFSv4.1 Parallel NFS is enabled.
	PnfsEnabled bool `json:"pnfs_enabled,omitempty"`
	// Specifies whether NFSv4.1 Read Delegation is enabled.
	ReadDelegationEnabled bool `json:"read_delegation_enabled,omitempty"`
	// Specifies whether NFSv4.1 Write Delegation is enabled.
	WriteDelegationEnabled bool `json:"write_delegation_enabled,omitempty"`
}
