/*
 * ONTAP REST API
 *
 * ONTAP 9.6 adds support for an expansive RESTful API. The documentation below provides information about the types of API calls available to you, as well as details about using each API endpoint. You can learn more about the ONTAP REST API and ONTAP in the ONTAP 9 Documentation Center:  http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-rest-api/home.html. NetApp welcomes your comments and suggestions about the ONTAP REST API and the documentation for its use.</br> **Using the ONTAP 9.6 REST API online documentation** Each API method includes usage examples, as well as a model that displays all the required and optional properties supported by the method. Click the _Model_ link, available with each API method, to see all the required and optional properties supported by each method. 
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ontap
// FpolicyEngine The engine defines how ONTAP makes and manages connections to external FPolicy servers.
type FpolicyEngine struct {
	// Specifies the name to assign to the external server configuration.
	Name string `json:"name,omitempty"`
	// Port number of the FPolicy server application.
	Port int32 `json:"port,omitempty"`
	PrimaryServers []string `json:"primary_servers,omitempty"`
	SecondaryServers []string `json:"secondary_servers,omitempty"`
	// The notification mode determines what ONTAP does after sending notifications to FPolicy servers.   The possible values are:     * synchronous  - After sending a notification, wait for a response from the FPolicy server.     * asynchronous - After sending a notification, file request processing continues. 
	Type string `json:"type,omitempty"`
}
