/*
 * ONTAP REST API
 *
 * ONTAP 9.6 adds support for an expansive RESTful API. The documentation below provides information about the types of API calls available to you, as well as details about using each API endpoint. You can learn more about the ONTAP REST API and ONTAP in the ONTAP 9 Documentation Center:  http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-rest-api/home.html. NetApp welcomes your comments and suggestions about the ONTAP REST API and the documentation for its use.</br> **Using the ONTAP 9.6 REST API online documentation** Each API method includes usage examples, as well as a model that displays all the required and optional properties supported by the method. Click the _Model_ link, available with each API method, to see all the required and optional properties supported by each method. 
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// When \"min_throughput_iops\", \"max_throughput_iops\" or \"max_throughput_mbps\" attributes are specified, the storage object is assigned to an auto-generated QoS policy group. If the attributes are later modified, the auto-generated QoS policy-group attributes are modified. Attributes can be removed by specifying \"0\" and policy group by specifying \"none\". Upon deletion of the storage object or if the attributes are removed, then the QoS policy-group is also removed.
type QosPolicyReference struct {
	Links *InlineResponse201Links `json:"_links,omitempty"`
	// Specifies the maximum throughput in IOPS, 0 means none. This is mutually exclusive with name and UUID during POST and PATCH. Default is 15000 on AFF platforms and 10000 on all other platforms.
	MaxThroughputIops int32 `json:"max_throughput_iops,omitempty"`
	// Specifies the maximum throughput in Megabytes per sec, 0 means none. This is mutually exclusive with name, UUID and \"min_throughput_iops\" during POST and PATCH.
	MaxThroughputMbps int32 `json:"max_throughput_mbps,omitempty"`
	// Specifies the minimum throughput in IOPS, 0 means none. Setting \"min_throughput\" is supported on AFF platforms only, unless FabricPool tiering policies are set. This is mutually exclusive with name, UUID and\" max_throughput_mbps\" during POST and PATCH.
	MinThroughputIops int32 `json:"min_throughput_iops,omitempty"`
	// The QoS policy group name. This is mutually exclusive with UUID and other QoS attributes during POST and PATCH.
	Name string `json:"name,omitempty"`
	// The QoS policy group UUID. This is mutually exclusive with name and other QoS attributes during POST and PATCH.
	Uuid string `json:"uuid,omitempty"`
}
