/*
 * ONTAP REST API
 *
 * ONTAP 9.6 adds support for an expansive RESTful API. The documentation below provides information about the types of API calls available to you, as well as details about using each API endpoint. You can learn more about the ONTAP REST API and ONTAP in the ONTAP 9 Documentation Center:  http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-rest-api/home.html. NetApp welcomes your comments and suggestions about the ONTAP REST API and the documentation for its use.</br> **Using the ONTAP 9.6 REST API online documentation** Each API method includes usage examples, as well as a model that displays all the required and optional properties supported by the method. Click the _Model_ link, available with each API method, to see all the required and optional properties supported by each method. 
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Properties of the transceiver connected to the FC port. 
type FcPortTransceiver struct {
	// The speeds of which the transceiver is capable in gigabits per second. 
	Capabilities []int32 `json:"capabilities,omitempty"`
	// The form factor of the transceiver. Possible values are: - _sfp_ - Small Form Factor - Pluggable - _sff_ - Small Form Factor - _unk_ - Unknown 
	FormFactor string `json:"form-factor,omitempty"`
	// The manufacturer of the transceiver. 
	Manufacturer string `json:"manufacturer,omitempty"`
	// The part number of the transceiver.
	PartNumber string `json:"part_number,omitempty"`
}
