/*
 * ONTAP REST API
 *
 * ONTAP 9.6 adds support for an expansive RESTful API. The documentation below provides information about the types of API calls available to you, as well as details about using each API endpoint. You can learn more about the ONTAP REST API and ONTAP in the ONTAP 9 Documentation Center:  http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-rest-api/home.html. NetApp welcomes your comments and suggestions about the ONTAP REST API and the documentation for its use.</br> **Using the ONTAP 9.6 REST API online documentation** Each API method includes usage examples, as well as a model that displays all the required and optional properties supported by the method. Click the _Model_ link, available with each API method, to see all the required and optional properties supported by each method. 
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Application Templates
type ApplicationTemplate struct {
	// Template Name. Required in the URL
	Name string `json:"name,omitempty"`
	// Description
	Description string `json:"description,omitempty"`
	MaxdataOnSan *MaxdataOnSan `json:"maxdata_on_san,omitempty"`
	// Missing Prerequisites
	MissingPrerequisites string `json:"missing_prerequisites,omitempty"`
	MongoDbOnSan *MongoDbOnSan `json:"mongo_db_on_san,omitempty"`
	Nas *Nas `json:"nas,omitempty"`
	OracleOnNfs *OracleOnNfs `json:"oracle_on_nfs,omitempty"`
	OracleOnSan *OracleOnSan `json:"oracle_on_san,omitempty"`
	OracleRacOnNfs *OracleRacOnNfs `json:"oracle_rac_on_nfs,omitempty"`
	OracleRacOnSan *OracleRacOnSan `json:"oracle_rac_on_san,omitempty"`
	// Access Protocol
	Protocol string `json:"protocol,omitempty"`
	San *San `json:"san,omitempty"`
	SqlOnSan *SqlOnSan `json:"sql_on_san,omitempty"`
	SqlOnSmb *SqlOnSmb `json:"sql_on_smb,omitempty"`
	VdiOnNas *VdiOnNas `json:"vdi_on_nas,omitempty"`
	VdiOnSan *VdiOnSan `json:"vdi_on_san,omitempty"`
	VsiOnNas *VsiOnNas `json:"vsi_on_nas,omitempty"`
	VsiOnSan *VsiOnSan `json:"vsi_on_san,omitempty"`
	Links *SelfLink `json:"_links,omitempty"`
}
