/*
 * ONTAP REST API
 *
 * ONTAP 9.6 adds support for an expansive RESTful API. The documentation below provides information about the types of API calls available to you, as well as details about using each API endpoint. You can learn more about the ONTAP REST API and ONTAP in the ONTAP 9 Documentation Center:  http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-rest-api/home.html. NetApp welcomes your comments and suggestions about the ONTAP REST API and the documentation for its use.</br> **Using the ONTAP 9.6 REST API online documentation** Each API method includes usage examples, as well as a model that displays all the required and optional properties supported by the method. Click the _Model_ link, available with each API method, to see all the required and optional properties supported by each method. 
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

// The Snapshot copy object represents a point in time Snapshot copy of a volume.
type Snapshot struct {
	Links *InlineResponse201Links `json:"_links,omitempty"`
	// A comment associated with the Snapshot copy. This is an optional attribute for POST or PATCH.
	Comment string `json:"comment,omitempty"`
	// Creation time of the Snapshot copy. It is the volume access time when the Snapshot copy was created.
	CreateTime time.Time `json:"create_time,omitempty"`
	// The expiry time for the Snapshot copy. This is an optional attribute for POST or PATCH. Snapshot copies with an expiry time set are not allowed to be deleted until the retention time is reached.
	ExpiryTime time.Time `json:"expiry_time,omitempty"`
	// Snapshot copy. Valid in POST or PATCH.
	Name string `json:"name,omitempty"`
	// SnapLock expiry time for the Snapshot copy, if the Snapshot copy is taken on a SnapLock volume. A Snapshot copy is not allowed to be deleted or renamed until the SnapLock ComplianceClock time goes beyond this retention time.
	SnaplockExpiryTime time.Time `json:"snaplock_expiry_time,omitempty"`
	// State of the Snapshot copy. There are cases where some Snapshot copies are not complete. In the \"partial\" state, the Snapshot copy is consistent but exists only on the subset of the constituents that existed prior to the FlexGroup's expansion. Partial Snapshot copies cannot be used for a Snapshot copy restore operation. A Snapshot copy is in an \"invalid\" state when it is present in some FlexGroup constituents but not in others. At all other times, a Snapshot copy is valid.
	State string `json:"state,omitempty"`
	Svm *AuditSvm `json:"svm,omitempty"`
	// The UUID of the Snapshot copy in the volume that uniquely identifies the Snapshot copy in that volume.
	Uuid string `json:"uuid,omitempty"`
	Volume *CifsShareVolume `json:"volume,omitempty"`
}
