/*
 * ONTAP REST API
 *
 * ONTAP 9.6 adds support for an expansive RESTful API. The documentation below provides information about the types of API calls available to you, as well as details about using each API endpoint. You can learn more about the ONTAP REST API and ONTAP in the ONTAP 9 Documentation Center:  http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-rest-api/home.html. NetApp welcomes your comments and suggestions about the ONTAP REST API and the documentation for its use.</br> **Using the ONTAP 9.6 REST API online documentation** Each API method includes usage examples, as well as a model that displays all the required and optional properties supported by the method. Click the _Model_ link, available with each API method, to see all the required and optional properties supported by each method. 
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Microsoft SQL using SAN.
type SqlOnSan struct {
	Db *SqlOnSanDb `json:"db,omitempty"`
	// The name of the initiator group through which the contents of this application will be accessed. Modification of this parameter is a disruptive operation. All LUNs in the application component will be unmapped from the current igroup and re-mapped to the new igroup. Required in the POST body and optional in the PATCH body
	IgroupName string `json:"igroup_name,omitempty"`
	Log *SqlOnSanLog `json:"log,omitempty"`
	// The list of initiator groups to create. Optional in the POST or PATCH body
	NewIgroups []SqlOnSanNewIgroups `json:"new_igroups,omitempty"`
	// The name of the host OS running the application. Optional in the POST body
	OsType string `json:"os_type,omitempty"`
	ProtectionType *MongoDbOnSanProtectionType `json:"protection_type,omitempty"`
	// The number of server cores for the db. Optional in the POST body
	ServerCoresCount int32 `json:"server_cores_count,omitempty"`
	TempDb *SqlOnSanTempDb `json:"temp_db,omitempty"`
}
