/*
 * ONTAP REST API
 *
 * ONTAP 9.6 adds support for an expansive RESTful API. The documentation below provides information about the types of API calls available to you, as well as details about using each API endpoint. You can learn more about the ONTAP REST API and ONTAP in the ONTAP 9 Documentation Center:  http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-rest-api/home.html. NetApp welcomes your comments and suggestions about the ONTAP REST API and the documentation for its use.</br> **Using the ONTAP 9.6 REST API online documentation** Each API method includes usage examples, as well as a model that displays all the required and optional properties supported by the method. Click the _Model_ link, available with each API method, to see all the required and optional properties supported by each method. 
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// An NVMe subsystem maintains configuration state and namespace access control for a set of NVMe-connected hosts. 
type NvmeSubsystem struct {
	Links *InlineResponse201Links `json:"_links,omitempty"`
	// A configurable comment for the NVMe subsystem. Optional in POST and PATCH. 
	Comment string `json:"comment,omitempty"`
	Hosts []NvmeSubsystemHosts `json:"hosts,omitempty"`
	IoQueue *NvmeSubsystemIoQueue `json:"io_queue,omitempty"`
	// The name of the NVMe subsystem. Once created, an NVMe subsystem cannot be renamed. Required in POST. 
	Name string `json:"name,omitempty"`
	// The host operating system of the NVMe subsystem's hosts. Required in POST. 
	OsType string `json:"os_type,omitempty"`
	// The serial number of the NVMe subsystem. 
	SerialNumber string `json:"serial_number,omitempty"`
	// The NVMe namespaces mapped to the NVMe subsystem.<br/> There is an added cost to retrieving property values for `subsystem_maps`. They are not populated for either a collection GET or an instance GET unless explicitly requested using the `fields` query parameter. See [`DOC Requesting specific fields`](#docs-docs-Requesting-specific-fields) to learn more. 
	SubsystemMaps []NvmeSubsystemSubsystemMaps `json:"subsystem_maps,omitempty"`
	Svm *AuditSvm `json:"svm,omitempty"`
	// The NVMe qualified name (NQN) used to identify the NVMe storage target. 
	TargetNqn string `json:"target_nqn,omitempty"`
	// The unique identifier of the NVMe subsystem. 
	Uuid string `json:"uuid,omitempty"`
}
