/*
 * ONTAP REST API
 *
 * ONTAP 9.6 adds support for an expansive RESTful API. The documentation below provides information about the types of API calls available to you, as well as details about using each API endpoint. You can learn more about the ONTAP REST API and ONTAP in the ONTAP 9 Documentation Center:  http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-rest-api/home.html. NetApp welcomes your comments and suggestions about the ONTAP REST API and the documentation for its use.</br> **Using the ONTAP 9.6 REST API online documentation** Each API method includes usage examples, as well as a model that displays all the required and optional properties supported by the method. Click the _Model_ link, available with each API method, to see all the required and optional properties supported by each method. 
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger
// ExportAuthenticationFlavor : Represents an authentication flavor. The following flavors are supported: * any - All authentication flavors * anon - Special authentication flavor for anonymization * never - Special authentication flavor to represent access denial * krb5 - Kerberos V4 Authentication * krb5i - Kerberos V4 Integrity * krb5p - Kerberos V4 Privacy * ntlm - CIFS NTLM Authentication * unix - AUTH_SYS or AUTH_UNIX Authentication 
type ExportAuthenticationFlavor string

// List of export_authentication_flavor
const (
	ANY_ExportAuthenticationFlavor ExportAuthenticationFlavor = "any"
	ANON_ExportAuthenticationFlavor ExportAuthenticationFlavor = "anon"
	NEVER_ExportAuthenticationFlavor ExportAuthenticationFlavor = "never"
	KRB5_ExportAuthenticationFlavor ExportAuthenticationFlavor = "krb5"
	KRB5I_ExportAuthenticationFlavor ExportAuthenticationFlavor = "krb5i"
	KRB5P_ExportAuthenticationFlavor ExportAuthenticationFlavor = "krb5p"
	NTLM_ExportAuthenticationFlavor ExportAuthenticationFlavor = "ntlm"
	UNIX_ExportAuthenticationFlavor ExportAuthenticationFlavor = "unix"
)
