/*
 * ONTAP REST API
 *
 * ONTAP 9.6 adds support for an expansive RESTful API. The documentation below provides information about the types of API calls available to you, as well as details about using each API endpoint. You can learn more about the ONTAP REST API and ONTAP in the ONTAP 9 Documentation Center:  http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-rest-api/home.html. NetApp welcomes your comments and suggestions about the ONTAP REST API and the documentation for its use.</br> **Using the ONTAP 9.6 REST API online documentation** Each API method includes usage examples, as well as a model that displays all the required and optional properties supported by the method. Click the _Model_ link, available with each API method, to see all the required and optional properties supported by each method. 
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type NfsServiceProtocol struct {
	// Specifies whether NFSv3 protocol is enabled.
	V3Enabled bool `json:"v3_enabled,omitempty"`
	// Specifies whether NFSv4.0 protocol is enabled.
	V40Enabled bool `json:"v40_enabled,omitempty"`
	V40Features *NfsServiceProtocolV40Features `json:"v40_features,omitempty"`
	// Specifies whether NFSv4.1 protocol is enabled.
	V41Enabled bool `json:"v41_enabled,omitempty"`
	V41Features *NfsServiceProtocolV41Features `json:"v41_features,omitempty"`
	// Specifies the domain portion of the string form of user and group names as defined by the NFSv4 protocol. 
	V4IdDomain string `json:"v4_id_domain,omitempty"`
}
