/*
 * ONTAP REST API
 *
 * ONTAP 9.6 adds support for an expansive RESTful API. The documentation below provides information about the types of API calls available to you, as well as details about using each API endpoint. You can learn more about the ONTAP REST API and ONTAP in the ONTAP 9 Documentation Center:  http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-rest-api/home.html. NetApp welcomes your comments and suggestions about the ONTAP REST API and the documentation for its use.</br> **Using the ONTAP 9.6 REST API online documentation** Each API method includes usage examples, as well as a model that displays all the required and optional properties supported by the method. Click the _Model_ link, available with each API method, to see all the required and optional properties supported by each method.
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ontap

// IscsiSession An iSCSI session is one or more TCP connections that link an iSCSI initiator with an iSCSI target. TCP connections can be added and removed from an iSCSI session by the iSCSI initiator. Across all TCP connections within an iSCSI session, an initiator sees one and the same target. After the connection is established, iSCSI control, data, and status messages are communicated over the session.
type IscsiSession struct {
	Links InlineResponse201Links `json:"_links,omitempty"`
	// The iSCSI connections that make up the iSCSI session.
	Connections []IscsiConnection `json:"connections,omitempty"`
	// The initiator groups in which the initiator is a member.
	Igroups   []FcLoginIgroups      `json:"igroups,omitempty"`
	Initiator IscsiSessionInitiator `json:"initiator,omitempty"`
	// The initiator portion of the session identifier specified by the initiator during login.
	Isid string   `json:"isid,omitempty"`
	Svm  AuditSvm `json:"svm,omitempty"`
	// The target portal group to which the session belongs.
	TargetPortalGroup string `json:"target_portal_group,omitempty"`
	// The target portal group tag of the session.
	TargetPortalGroupTag int32 `json:"target_portal_group_tag,omitempty"`
	// The target session identifier handle (TSIH) of the session.
	Tsih int32 `json:"tsih,omitempty"`
}
