/*
 * ONTAP REST API
 *
 * ONTAP 9.6 adds support for an expansive RESTful API. The documentation below provides information about the types of API calls available to you, as well as details about using each API endpoint. You can learn more about the ONTAP REST API and ONTAP in the ONTAP 9 Documentation Center:  http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-rest-api/home.html. NetApp welcomes your comments and suggestions about the ONTAP REST API and the documentation for its use.</br> **Using the ONTAP 9.6 REST API online documentation** Each API method includes usage examples, as well as a model that displays all the required and optional properties supported by the method. Click the _Model_ link, available with each API method, to see all the required and optional properties supported by each method.
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ontap

// CloudTarget struct for CloudTarget
type CloudTarget struct {
	Links InlineResponse201Links `json:"_links,omitempty"`
	// Access key ID for AWS_S3 and other S3 compatible provider types.
	AccessKey string `json:"access_key,omitempty"`
	// Authentication used to access the target. Snapmirror does not yet support CAP. Required in POST.
	AuthenticationType string `json:"authentication_type,omitempty"`
	// Azure account
	AzureAccount string `json:"azure_account,omitempty"`
	// Azure access key
	AzurePrivateKey string `json:"azure_private_key,omitempty"`
	// This parameter is available only when auth-type is CAP. It specifies a full URL of the request to a CAP server for retrieving temporary credentials (access-key, secret-pasword, and session token) for accessing the object store.
	CapUrl string `json:"cap_url,omitempty"`
	// Is SSL/TLS certificate validation enabled? The default value is true. This can only be modified for SGWS and IBM_COS provider types.
	CertificateValidationEnabled bool `json:"certificate_validation_enabled,omitempty"`
	// Data bucket/container name
	Container string             `json:"container,omitempty"`
	Ipspace   CloudTargetIpspace `json:"ipspace,omitempty"`
	// Cloud target name
	Name string `json:"name,omitempty"`
	// Owner of the target. Allowed values are FabricPool or SnapMirror. A target can be used by only one feature.
	Owner string `json:"owner,omitempty"`
	// Port number of the object store that ONTAP uses when establishing a connection. Required in POST.
	Port int32 `json:"port,omitempty"`
	// Type of cloud provider. Allowed values depend on owner type. For FabricPool, AliCloud, AWS_S3, Azure_Cloud, GoggleCloud, IBM_COS, and SGWS are allowed. For SnapMirror, the valid values are AWS_S3 or SGWS.
	ProviderType string `json:"provider_type,omitempty"`
	// Secret access key for AWS_S3 and other S3 compatible provider types.
	SecretPassword string `json:"secret_password,omitempty"`
	// Fully qualified domain name of the object store server. Required on POST.  For Amazon S3, server name must be an AWS regional endpoint in the format s3.amazonaws.com or s3-<region>.amazonaws.com, for example, s3-us-west-2.amazonaws.com. The region of the server and the bucket must match. For Azure, if the server is a \"blob.core.windows.net\" or a \"blob.core.usgovcloudapi.net\", then a value of azure-account followed by a period is added in front of the server.
	Server string `json:"server,omitempty"`
	// Use of the cloud target by SnapMirror.
	SnapmirrorUse string `json:"snapmirror_use,omitempty"`
	// SSL/HTTPS enabled or not
	SslEnabled bool           `json:"ssl_enabled,omitempty"`
	Svm        CloudTargetSvm `json:"svm,omitempty"`
	// The amount of cloud space used by all the aggregates attached to the target, in bytes. This field is only populated for FabricPool targets. The value is recalculated once every 5 minutes.
	Used int32 `json:"used,omitempty"`
	// Cloud target UUID
	Uuid string `json:"uuid,omitempty"`
}
