/*
 * ONTAP REST API
 *
 * ONTAP 9.6 adds support for an expansive RESTful API. The documentation below provides information about the types of API calls available to you, as well as details about using each API endpoint. You can learn more about the ONTAP REST API and ONTAP in the ONTAP 9 Documentation Center:  http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-rest-api/home.html. NetApp welcomes your comments and suggestions about the ONTAP REST API and the documentation for its use.</br> **Using the ONTAP 9.6 REST API online documentation** Each API method includes usage examples, as well as a model that displays all the required and optional properties supported by the method. Click the _Model_ link, available with each API method, to see all the required and optional properties supported by each method.
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ontap

// FcLoginInitiator Information about the logged in FC initiator.
type FcLoginInitiator struct {
	// The logged in initiator world wide port name (WWPN) aliases.
	Aliases []string `json:"aliases,omitempty"`
	// The port address of the initiator's FC port.<br/> Each port in an FC switched fabric has its own unique port address for routing purposes. The port address is assigned by a switch in the fabric when that port logs in to the fabric. This property refers to the address given by a switch to the initiator port.<br/> This is useful for obtaining statistics and diagnostic information from FC switches.<br/> This is a hexadecimal encoded numeric value.
	PortAddress string `json:"port_address,omitempty"`
	// The logged in initiator world wide node name (WWNN).
	Wwnn string `json:"wwnn,omitempty"`
	// The logged in initiator WWPN.
	Wwpn string `json:"wwpn,omitempty"`
}
