/*
 * ONTAP REST API
 *
 * ONTAP 9.6 adds support for an expansive RESTful API. The documentation below provides information about the types of API calls available to you, as well as details about using each API endpoint. You can learn more about the ONTAP REST API and ONTAP in the ONTAP 9 Documentation Center:  http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-rest-api/home.html. NetApp welcomes your comments and suggestions about the ONTAP REST API and the documentation for its use.</br> **Using the ONTAP 9.6 REST API online documentation** Each API method includes usage examples, as well as a model that displays all the required and optional properties supported by the method. Click the _Model_ link, available with each API method, to see all the required and optional properties supported by each method.
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ontap

// LdapService struct for LdapService
type LdapService struct {
	Links InlineResponse201Links `json:"_links,omitempty"`
	// This parameter specifies the name of the Active Directory domain used to discover LDAP servers for use by this client. This is mutually exclusive with `servers` during POST and PATCH.
	AdDomain string `json:"ad_domain,omitempty"`
	// Specifies the default base DN for all searches.
	BaseDn string `json:"base_dn,omitempty"`
	// Specifies the default search scope for LDAP queries: * base - search the named entry only * onelevel - search all entries immediately below the DN * subtree - search the named DN entry and the entire subtree below the DN
	BaseScope string `json:"base_scope,omitempty"`
	// Specifies the user that binds to the LDAP servers.
	BindDn string `json:"bind_dn,omitempty"`
	// Specifies the bind password for the LDAP servers.
	BindPassword string `json:"bind_password,omitempty"`
	// The minimum bind authentication level. Possible values are: * anonymous - anonymous bind * simple - simple bind * sasl - Simple Authentication and Security Layer (SASL) bind
	MinBindLevel string `json:"min_bind_level,omitempty"`
	// The port used to connect to the LDAP Servers.
	Port               int32    `json:"port,omitempty"`
	PreferredAdServers []string `json:"preferred_ad_servers,omitempty"`
	// The name of the schema template used by the SVM. * AD-IDMU - Active Directory Identity Management for UNIX * AD-SFU - Active Directory Services for UNIX * MS-AD-BIS - Active Directory Identity Management for UNIX * RFC-2307 - Schema based on RFC 2307 * Custom schema
	Schema  string   `json:"schema,omitempty"`
	Servers []string `json:"servers,omitempty"`
	// Specifies the level of security to be used for LDAP communications: * none - no signing or sealing * sign - sign LDAP traffic * seal - seal and sign LDAP traffic
	SessionSecurity string `json:"session_security,omitempty"`
	Svm             DnsSvm `json:"svm,omitempty"`
	// Specifies whether or not to use Start TLS over LDAP connections.
	UseStartTls bool `json:"use_start_tls,omitempty"`
}
